F4play:
	gcc -Wall src/F4Client.c src/errExit.c src/semaphore.c src/shared_memory.c -o F4Client
	gcc -Wall src/F4Server.c src/errExit.c src/semaphore.c src/shared_memory.c -o F4Server
	gcc -Wall src/F4ClientBot.c src/errExit.c src/semaphore.c src/shared_memory.c -o F4ClientBot
